/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProduitRequest } from '../../models/produit-request';
import { ProduitResponse } from '../../models/produit-response';

export interface CreateProduit$Params {
      body: ProduitRequest
}

export function createProduit(http: HttpClient, rootUrl: string, params: CreateProduit$Params, context?: HttpContext): Observable<StrictHttpResponse<ProduitResponse>> {
  const rb = new RequestBuilder(rootUrl, createProduit.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProduitResponse>;
    })
  );
}

createProduit.PATH = '/api/v4/gestion/produit';
