/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageProduitResponse } from '../../models/page-produit-response';

export interface FindAllProduits$Params {
  pageable: Pageable;
}

export function findAllProduits(http: HttpClient, rootUrl: string, params: FindAllProduits$Params, context?: HttpContext): Observable<StrictHttpResponse<PageProduitResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllProduits.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageProduitResponse>;
    })
  );
}

findAllProduits.PATH = '/api/v4/gestion/produit';
