/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProduitResponse } from '../../models/produit-response';

export interface GetProduitById$Params {
  produitId: string;
}

export function getProduitById(http: HttpClient, rootUrl: string, params: GetProduitById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProduitResponse>> {
  const rb = new RequestBuilder(rootUrl, getProduitById.PATH, 'get');
  if (params) {
    rb.path('produitId', params.produitId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProduitResponse>;
    })
  );
}

getProduitById.PATH = '/api/v4/gestion/produit/{produitId}';
