/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ZoneResponse } from '../../models/zone-response';

export interface GetZone$Params {
  zoneId: string;
}

export function getZone(http: HttpClient, rootUrl: string, params: GetZone$Params, context?: HttpContext): Observable<StrictHttpResponse<ZoneResponse>> {
  const rb = new RequestBuilder(rootUrl, getZone.PATH, 'get');
  if (params) {
    rb.path('zoneId', params.zoneId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ZoneResponse>;
    })
  );
}

getZone.PATH = '/api/v4/gestion/zone/{zoneId}';
