/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionResponseDetail } from '../models/permission-response-detail';
import { RolesResponse } from '../models/roles-response';
export interface AssignResponse {
  permissions?: Array<PermissionResponseDetail>;
  role?: RolesResponse;
}
