/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolesEntity } from '../models/roles-entity';
export interface AuthResponse {
  email?: string;
  nom?: string;
  prenom?: string;
  role?: RolesEntity;
  token?: string;
}
