/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientDestinataireResponse {
  adresse?: string;
  email?: string;
  id?: string;
  nom?: string;
  prenom?: string;
  role?: string;
  telephone?: string;
}
