/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientDestinataireRequest {
  adresse: string;
  email?: string;
  nom: string;
  prenom: string;
  telephone: string;
}
