/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientDestinataireResponseBasic } from '../models/client-destinataire-response-basic';
import { ZoneResponse } from '../models/zone-response';
export interface ColisResponseBasic {
  clientExpediteur?: ClientDestinataireResponseBasic;
  dateCreation?: string;
  description?: string;
  destinataire?: ClientDestinataireResponseBasic;
  id?: string;
  poids?: number;
  priorite?: string;
  statut?: string;
  villeDestination?: string;
  zone?: ZoneResponse;
  zoneOrigine?: ZoneResponse;
}
