/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientDestinataireResponse } from '../models/client-destinataire-response';
import { ColisProduitResponse } from '../models/colis-produit-response';
import { HistoriqueLivraisonResponse } from '../models/historique-livraison-response';
import { LivreurResponse } from '../models/livreur-response';
import { ZoneResponse } from '../models/zone-response';
export interface ColisResponse {
  clientExpediteur?: ClientDestinataireResponse;
  dateCreation?: string;
  description?: string;
  destinataire?: ClientDestinataireResponse;
  historique?: Array<HistoriqueLivraisonResponse>;
  id?: string;
  livreur?: LivreurResponse;
  poids?: number;
  priorite?: string;
  produits?: Array<ColisProduitResponse>;
  statut?: string;
  villeDestination?: string;
  zone?: ZoneResponse;
  zoneOrigine?: ZoneResponse;
}
