/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RolesEntity } from '../models/roles-entity';
export interface GestionResponse {
  id?: string;
  nom?: string;
  prenom?: string;
  role?: RolesEntity;
  telephone?: string;
}
