/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface HistoriqueLivraisonResponse {
  commentaire?: string;
  dateChangement?: string;
  id?: string;
  statut?: string;
}
