/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LivreurRequest {
  confirmPassword: string;
  email?: string;
  nom: string;
  password: string;
  prenom: string;
  telephone: string;
  vehicule: string;
  zoneAssigneeId: string;
}
