/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Pageablenull } from '../models/pageablenull';
import { PermissionResponseDetail } from '../models/permission-response-detail';
import { Sortnull } from '../models/sortnull';
export interface PagePermissionResponseDetail {
  content?: Array<PermissionResponseDetail>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: Pageablenull;
  size?: number;
  sort?: Sortnull;
  totalElements?: number;
  totalPages?: number;
}
