/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sortnull } from '../models/sortnull';
export interface Pageablenull {
  offset?: number;
  pageNumber?: number;
  pageSize?: number;
  paged?: boolean;
  sort?: Sortnull;
  unpaged?: boolean;
}
