/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GestionResponse } from '../models/gestion-response';
import { Pageablenull } from '../models/pageablenull';
import { Sortnull } from '../models/sortnull';
export interface PageGestionResponse {
  content?: Array<GestionResponse>;
  empty?: boolean;
  first?: boolean;
  last?: boolean;
  number?: number;
  numberOfElements?: number;
  pageable?: Pageablenull;
  size?: number;
  sort?: Sortnull;
  totalElements?: number;
  totalPages?: number;
}
