/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Permission {
  createdBy?: string;
  dateCreation?: string;
  dateModification?: string;
  id?: string;
  modifiedBy?: string;
  name?: string;
}
