/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AssignRequest } from '../../models/assign-request';
import { AssignResponse } from '../../models/assign-response';

export interface AssignPermissionToRole$Params {
      body: AssignRequest
}

export function assignPermissionToRole(http: HttpClient, rootUrl: string, params: AssignPermissionToRole$Params, context?: HttpContext): Observable<StrictHttpResponse<AssignResponse>> {
  const rb = new RequestBuilder(rootUrl, assignPermissionToRole.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AssignResponse>;
    })
  );
}

assignPermissionToRole.PATH = '/api/admin/Roles/AssignPermission';
