/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageClientDestinataireResponse } from '../../models/page-client-destinataire-response';

export interface SearchClients$Params {
  keyword: string;
  pageable: Pageable;
}

export function searchClients(http: HttpClient, rootUrl: string, params: SearchClients$Params, context?: HttpContext): Observable<StrictHttpResponse<PageClientDestinataireResponse>> {
  const rb = new RequestBuilder(rootUrl, searchClients.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageClientDestinataireResponse>;
    })
  );
}

searchClients.PATH = '/api/v3/clients/search';
