/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientDestinataireRequest } from '../../models/client-destinataire-request';
import { ClientDestinataireResponse } from '../../models/client-destinataire-response';

export interface UpdateClient$Params {
  clientId: string;
      body: ClientDestinataireRequest
}

export function updateClient(http: HttpClient, rootUrl: string, params: UpdateClient$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientDestinataireResponse>> {
  const rb = new RequestBuilder(rootUrl, updateClient.PATH, 'put');
  if (params) {
    rb.path('clientId', params.clientId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientDestinataireResponse>;
    })
  );
}

updateClient.PATH = '/api/v3/clients/{clientId}';
