/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LivreurRequest } from '../../models/livreur-request';
import { LivreurResponse } from '../../models/livreur-response';

export interface CreateLivreur$Params {
      body: LivreurRequest
}

export function createLivreur(http: HttpClient, rootUrl: string, params: CreateLivreur$Params, context?: HttpContext): Observable<StrictHttpResponse<LivreurResponse>> {
  const rb = new RequestBuilder(rootUrl, createLivreur.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LivreurResponse>;
    })
  );
}

createLivreur.PATH = '/api/v1/gestionner/livreur';
