/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LivreurResponse } from '../../models/livreur-response';

export interface GetLivreurById$Params {

/**
 * ID unique du livreur
 */
  livreur_id: string;
}

export function getLivreurById(http: HttpClient, rootUrl: string, params: GetLivreurById$Params, context?: HttpContext): Observable<StrictHttpResponse<LivreurResponse>> {
  const rb = new RequestBuilder(rootUrl, getLivreurById.PATH, 'get');
  if (params) {
    rb.path('livreur_id', params.livreur_id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LivreurResponse>;
    })
  );
}

getLivreurById.PATH = '/api/v1/gestionner/livreur/{livreur_id}';
