/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageLivreurResponse } from '../../models/page-livreur-response';

export interface SearchLivreurs$Params {

/**
 * Mot-clé pour la recherche par Nom, Prénom, ou Téléphone.
 */
  keyword?: string;
  pageable: Pageable;
}

export function searchLivreurs(http: HttpClient, rootUrl: string, params: SearchLivreurs$Params, context?: HttpContext): Observable<StrictHttpResponse<PageLivreurResponse>> {
  const rb = new RequestBuilder(rootUrl, searchLivreurs.PATH, 'get');
  if (params) {
    rb.query('keyword', params.keyword, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageLivreurResponse>;
    })
  );
}

searchLivreurs.PATH = '/api/v1/gestionner/livreur/search';
