/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ColisResponse } from '../../models/colis-response';

export interface AssignColisToLivreur$Params {
  colisId: string;
  livreurId: string;
}

export function assignColisToLivreur(http: HttpClient, rootUrl: string, params: AssignColisToLivreur$Params, context?: HttpContext): Observable<StrictHttpResponse<ColisResponse>> {
  const rb = new RequestBuilder(rootUrl, assignColisToLivreur.PATH, 'put');
  if (params) {
    rb.path('colisId', params.colisId, {});
    rb.query('livreurId', params.livreurId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ColisResponse>;
    })
  );
}

assignColisToLivreur.PATH = '/api/v2/colis/gestionner/livreur/{colisId}/assign';
