/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageColisResponse } from '../../models/page-colis-response';

export interface GetColisByExpediteur$Params {
  expediteurId: string;
  pageable: Pageable;
}

export function getColisByExpediteur(http: HttpClient, rootUrl: string, params: GetColisByExpediteur$Params, context?: HttpContext): Observable<StrictHttpResponse<PageColisResponse>> {
  const rb = new RequestBuilder(rootUrl, getColisByExpediteur.PATH, 'get');
  if (params) {
    rb.path('expediteurId', params.expediteurId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageColisResponse>;
    })
  );
}

getColisByExpediteur.PATH = '/api/v2/colis/expediteur/{expediteurId}';
