/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageColisResponseBasic } from '../../models/page-colis-response-basic';

export interface GetAllColis$Params {
  page?: number;
  size?: number;
  sortBy?: string;
  sortDir?: string;
}

export function getAllColis(http: HttpClient, rootUrl: string, params?: GetAllColis$Params, context?: HttpContext): Observable<StrictHttpResponse<PageColisResponseBasic>> {
  const rb = new RequestBuilder(rootUrl, getAllColis.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
    rb.query('sortBy', params.sortBy, {});
    rb.query('sortDir', params.sortDir, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageColisResponseBasic>;
    })
  );
}

getAllColis.PATH = '/api/v2/colis';
