/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageHistoriqueLivraisonResponse } from '../../models/page-historique-livraison-response';

export interface GetColisHistory$Params {
  colisId: string;
  pageable: Pageable;
}

export function getColisHistory(http: HttpClient, rootUrl: string, params: GetColisHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<PageHistoriqueLivraisonResponse>> {
  const rb = new RequestBuilder(rootUrl, getColisHistory.PATH, 'get');
  if (params) {
    rb.path('colisId', params.colisId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageHistoriqueLivraisonResponse>;
    })
  );
}

getColisHistory.PATH = '/api/v2/colis/{colisId}/history';
